resource.charset=UTF8
resource.background.path=${path.resource}/bg.eng.res
#resource.background.corpus.path=${path.resource}/bg.corpus
resource.public.sentiment.positive=${path.resource}/pos.eng.res
resource.public.sentiment.negative=${path.resource}/neg.eng.res
resource.public.sentiment.neutral=${path.resource}/neu.eng.res
resource.public.sentiment.inverse.adverb=${path.resource}/iadv.eng.res
resource.public.sentiment.inverse.conjuction=${path.resource}/iconj.eng.res